services:
  frontend_dev:
    build:
      dockerfile: Dockerfile.dev
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_GOOGLE_OAUTH2_CLIENT_ID: ${VITE_GOOGLE_OAUTH2_CLIENT_ID}
    ports:
      - '5173:5173'
  frontend_prod:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_GOOGLE_OAUTH2_CLIENT_ID: ${VITE_GOOGLE_OAUTH2_CLIENT_ID}
    ports:
      - '80:80'
